package com.example.payments.model;

public enum ErrorCode {
    VALIDATION_FAILED,
    INVALID_ACCOUNT,
    INVALID_CURRENCY,
    INVALID_AMOUNT,
    INVALID_STATUS_TRANSITION,
    PAYMENT_NOT_FOUND,
    NETWORK_ERROR,
    PROCESSING_ERROR,
    INVALID_ACCOUNT_OWNERSHIP,
    ACCOUNT_NOT_FOUND,
    IDEMPOTENCY_KEY_REUSED,
    INSUFFICIENT_FUNDS,
    LIMIT_EXCEEDED,
    CONCURRENT_UPDATE,
    UNAUTHORIZED,
    PAYEE_NOT_FOUND,
    INTENT_NOT_FOUND,
    INTENT_EXPIRED,
    INTENT_ALREADY_CONVERTED
}
