server.port=8080

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/payment_mvp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=n3u3da!

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=2

# Payment config
payment.currency.base=USD
payment.currency.usd-to-usd=1.0
payment.currency.eur-to-usd=1.08
payment.currency.gbp-to-usd=1.27
payment.currency.inr-to-usd=0.012
payment.send.success-rate=0.8
payment.send.max-retries=3
payment.send.backoff-base-millis=1000
payment.limits.max-transaction-amount=10000
payment.intent.expiry-minutes=30
payment.single-user.email=single.user@local
payment.single-user.full-name=Single User
payment.single-user.account-number=ACC-001

# Actuator
management.endpoints.web.base-path=/api/actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
